export enum OrderStatus {
  ORDER_PLACED = 'ORDER_PLACED',
  PAYMENT_PENDING = 'PAYMENT_PENDING',
  PAYMENT_SUCCESS = 'PAYMENT_SUCCESS',
  DESIGN_APPROVED = 'DESIGN_APPROVED',
  PRINTING_STARTED = 'PRINTING_STARTED',
  PRINTING_COMPLETED = 'PRINTING_COMPLETED',
  PACKED = 'PACKED',
  DISPATCHED = 'DISPATCHED',
  IN_TRANSIT = 'IN_TRANSIT',
  OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
}

export enum ReturnStatus {
  RETURN_REQUESTED = 'RETURN_REQUESTED',
  RETURN_UNDER_REVIEW = 'RETURN_UNDER_REVIEW',
  RETURN_APPROVED = 'RETURN_APPROVED',
  PICKUP_SCHEDULED = 'PICKUP_SCHEDULED',
  PICKED_UP = 'PICKED_UP',
  RETURN_RECEIVED = 'RETURN_RECEIVED',
  REFUND_APPROVED = 'REFUND_APPROVED',
  REFUND_PROCESSED = 'REFUND_PROCESSED',
  REFUND_COMPLETED = 'REFUND_COMPLETED',
}
